import { GroupConfig, GroupConfigurations } from "@/app/types";

const groupConfig: GroupConfigurations = {
    AllIndiaStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        displayLabel: 'All India',
        region: 'Other States',
    },
    EnableStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'NVS Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no NVS live test for today!',
        testsInfoLink: 'https://www.nvslakshya.org/nvs-test-details',
        showLibraryTab: true,
        showReportsTab: true,
        testsHeaderNote: "You're seeing the test based on the exam preference shared by your school. If you see more than one test, select your preferred one from below",
        displayLabel: 'Enable Students (NVS)',
        region: 'NVS / Enable',
    },
    EnableSchools: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        showHomeTab: false,
        displayLabel: 'Enable Schools',
        region: 'NVS / Enable',
    },
    DelhiStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'CM Shri Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no CM Shri live test for today!',
        displayLabel: 'Delhi Students',
        region: 'Delhi',
    },
    defaultGroup: {
        showLiveClasses: true,
        showTests: true,
        showPracticeTests: true,
        showHomework: true,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
    },
    ChhattisgarhStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        displayLabel: 'Chhattisgarh',
        region: 'Other States',
    },
    PunjabStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'PACE State-wide Test (Live)',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no PACE live test for today!',
        displayLabel: 'Punjab Students',
        region: 'Punjab',
    },
    PunjabTeachers: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        showHomeTab: false,
        showLibraryTab: true,
        showReportsTab: false,
        displayLabel: 'Punjab Teachers',
        region: 'Punjab',
    },
    DelhiSchools: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        showHomeTab: false,
        noReportsMessage: 'The reports will be available once the first test has been completed',
        displayLabel: 'Delhi Schools',
        region: 'Delhi',
    },
    HimachalStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Himachal State-wide Test (Live)',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no Himachal live test for today!',
        displayLabel: 'Himachal Pradesh',
        region: 'Other States',
    },
    UttarakhandStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Uttarakhand State-wide Test (Live)',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no Uttarakhand live test for today!',
        displayLabel: 'Uttarakhand',
        region: 'Other States',
    },
    MaharashtraStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no live test for today!',
        displayLabel: 'Maharashtra',
        region: 'Other States',
    },
    TNTeachers: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: false,
        showClassLibrary: false,
        testsSectionTitle: 'Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no live test for today!',
        showLibraryTab: false,
        showReportsTab: false,
        displayLabel: 'Tamil Nadu (Teachers)',
        region: 'Other States',
    },
};

export const LOGIN_REGION_ORDER = ["Delhi", "Punjab", "NVS / Enable", "Other States"];

export const getGroupConfig = (group: string): GroupConfig => {
    return groupConfig[group] || groupConfig.defaultGroup;
};

export default groupConfig;
