import { GroupConfig, GroupConfigurations } from "@/app/types";

const groupConfig: GroupConfigurations = {
    AllIndiaStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
    },
    EnableStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'NVS Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no NVS live test for today!',
        testsInfoLink: 'https://www.nvslakshya.org/nvs-test-details',
        showLibraryTab: true,
        showReportsTab: true,
        testsHeaderNote: "You’re seeing the test based on the exam preference shared by your school. If you see more than one test, select your preferred one from below",
    },
    EnableSchools: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        showHomeTab: false,
    },
    DelhiStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'CM Shri Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no CM Shri live test for today!',
    },
    defaultGroup: {
        showLiveClasses: true,
        showTests: true,
        showPracticeTests: true,
        showHomework: true,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
    },
    ChhattisgarhStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
    },
    PunjabStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'PACE State-wide Test (Live)',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no PACE live test for today!',
    },
    PunjabTeachers: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        showHomeTab: false,
        showLibraryTab: true,
        showReportsTab: false,
    },
    DelhiSchools: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        showHomeTab: false,
        noReportsMessage: 'The reports will be available once the first test has been completed',
    },
    HimachalStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Himachal State-wide Test (Live)',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no Himachal live test for today!',
    },
    UttarakhandStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Uttarakhand State-wide Test (Live)',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no Uttarakhand live test for today!',
    },
    MaharashtraStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no live test for today!',
    },
};

export const getGroupConfig = (group: string): GroupConfig => {
    return groupConfig[group] || groupConfig.defaultGroup;
};

export default groupConfig;