import { GroupConfig, GroupConfigurations } from "@/app/types";

const groupConfig: GroupConfigurations = {
    AllIndiaStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
    },
    EnableStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'NVS Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no NVS live test for today!',
        testsInfoLink: 'https://www.nvslakshya.org/nvs-test-details',
    },
    EnableSchools: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        showHomeTab: false,
    },
    DelhiStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'CM Shri Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no CM Shri live test for today!',
    },
    defaultGroup: {
        showLiveClasses: true,
        showTests: true,
        showPracticeTests: true,
        showHomework: true,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
    },
    ChhattisgarhStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
    },
    PunjabStudents: {
        showLiveClasses: false,
        showTests: true,
        showPracticeTests: true,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'PACE Live Test',
        homeTabLabel: 'Tests',
        noTestsMessage: 'There is no PACE live test for today!',
    },
    DelhiSchools: {
        showLiveClasses: false,
        showTests: false,
        showPracticeTests: false,
        showHomework: false,
        showContentLibrary: true,
        showClassLibrary: false,
        testsSectionTitle: 'Tests',
        homeTabLabel: 'Home',
        showHomeTab: false,
        noReportsMessage: 'The reports will be available once the first test has been completed',
    },
};

export const getGroupConfig = (group: string): GroupConfig => {
    return groupConfig[group] || groupConfig.defaultGroup;
};

export default groupConfig;